//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class faktura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public faktura()
        {
            this.fakturaStavke = new HashSet<fakturaStavke>();
        }
    
        public int fakturaId { get; set; }
        public Nullable<int> klijentId { get; set; }
        public Nullable<System.DateTime> datumFakture { get; set; }
        public Nullable<System.DateTime> datumValute { get; set; }
        public Nullable<System.DateTime> fakturisanoOd { get; set; }
        public Nullable<System.DateTime> fakturisanoDo { get; set; }
        public Nullable<decimal> iznosBezPdv { get; set; }
        public Nullable<decimal> pdv { get; set; }
        public Nullable<decimal> iznosSaPdv { get; set; }
        public Nullable<int> valutaId { get; set; }
        public Nullable<decimal> iznosValuta { get; set; }
        public Nullable<int> ponudaId { get; set; }
        public Nullable<int> brojFakture { get; set; }
    
        public virtual klijent klijent { get; set; }
        public virtual ponuda ponuda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fakturaStavke> fakturaStavke { get; set; }
    }
}
