//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class fakturaStavke
    {
        public int fakturaStavkeId { get; set; }
        public Nullable<int> fakturaId { get; set; }
        public Nullable<int> plakatId { get; set; }
        public Nullable<int> trosakId { get; set; }
        public Nullable<decimal> kolicina { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<decimal> rabat { get; set; }
        public Nullable<decimal> cijenaSaPopustom { get; set; }
        public Nullable<int> ponudaStavkaId { get; set; }
    
        public virtual faktura faktura { get; set; }
        public virtual plakat plakat { get; set; }
        public virtual trosak trosak { get; set; }
        public virtual ponudaStavke ponudaStavke { get; set; }
    }
}
