//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class klijent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klijent()
        {
            this.faktura = new HashSet<faktura>();
            this.klijentVeze = new HashSet<klijentVeze>();
            this.klijentVeze1 = new HashSet<klijentVeze>();
            this.plakat = new HashSet<plakat>();
            this.ponuda = new HashSet<ponuda>();
            this.ponuda1 = new HashSet<ponuda>();
            this.ponuda2 = new HashSet<ponuda>();
            this.ponuda3 = new HashSet<ponuda>();
            this.ugovor = new HashSet<ugovor>();
        }
    
        public int klijentId { get; set; }
        public string naziv { get; set; }
        public Nullable<int> klijentTipId { get; set; }
        public Nullable<int> klijentVrstaId { get; set; }
        public string JIB { get; set; }
        public string PDVBroj { get; set; }
        public string posta { get; set; }
        public Nullable<int> mjestoId { get; set; }
        public string adresa { get; set; }
        public string telefon { get; set; }
        public string eMail { get; set; }
        public string kontaktOsoba { get; set; }
        public string odgovornaOsoba { get; set; }
        public string webStranica { get; set; }
        public Nullable<int> valutaId { get; set; }
        public Nullable<bool> isPdv { get; set; }
        public Nullable<bool> aktivan { get; set; }
        public Nullable<int> jezikId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<faktura> faktura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<klijentVeze> klijentVeze { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<klijentVeze> klijentVeze1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plakat> plakat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ponuda> ponuda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ponuda> ponuda1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ponuda> ponuda2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ponuda> ponuda3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ugovor> ugovor { get; set; }
    }
}
