//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mrezaPlakat
    {
        public int mrezaPlakatId { get; set; }
        public Nullable<int> mrezaId { get; set; }
        public Nullable<int> plakatId { get; set; }
        public Nullable<System.DateTime> datumOd { get; set; }
        public Nullable<System.DateTime> datumDo { get; set; }
    
        public virtual plakat plakat { get; set; }
    }
}
