//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plakat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public plakat()
        {
            this.fakturaStavke = new HashSet<fakturaStavke>();
            this.mrezaPlakat = new HashSet<mrezaPlakat>();
            this.plakatSlika = new HashSet<plakatSlika>();
            this.ponudaStavke = new HashSet<ponudaStavke>();
            this.ugovorStavke = new HashSet<ugovorStavke>();
        }
    
        public int plakatId { get; set; }
        public Nullable<int> inventarniBroj { get; set; }
        public Nullable<int> redniBroj { get; set; }
        public string posta { get; set; }
        public Nullable<int> mjestoId { get; set; }
        public string adresa { get; set; }
        public Nullable<int> plakatTipId { get; set; }
        public System.Data.Entity.Spatial.DbGeography koordinate { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<bool> isOsvjetljen { get; set; }
        public Nullable<bool> isDvostrano { get; set; }
        public Nullable<int> plakatKategorijaIzvrsnostiId { get; set; }
        public Nullable<int> vlasnikId { get; set; }
        public Nullable<int> cjenovnaKategorijaId { get; set; }
        public Nullable<int> statusPlakatId { get; set; }
        public string dimenzija { get; set; }
        public Nullable<int> vrstaOkviraId { get; set; }
        public Nullable<int> dimenzijaId { get; set; }
        public Nullable<int> turaId { get; set; }
        public Nullable<int> zaposleniId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fakturaStavke> fakturaStavke { get; set; }
        public virtual klijent klijent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mrezaPlakat> mrezaPlakat { get; set; }
        public virtual zaposleni zaposleni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<plakatSlika> plakatSlika { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ponudaStavke> ponudaStavke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ugovorStavke> ugovorStavke { get; set; }
    }
}
