//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class plakatLog
    {
        public int plakatId { get; set; }
        public Nullable<int> inventarniBroj { get; set; }
        public Nullable<int> redniBroj { get; set; }
        public string posta { get; set; }
        public Nullable<int> mjestoId { get; set; }
        public string adresa { get; set; }
        public Nullable<int> plakatTipId { get; set; }
        public System.Data.Entity.Spatial.DbGeography koordinate { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<bool> isOsvjetljen { get; set; }
        public Nullable<bool> isDvostrano { get; set; }
        public Nullable<int> plakatKategorijaIzvrsnostiId { get; set; }
        public Nullable<int> vlasnikId { get; set; }
        public Nullable<int> cjenovnaKategorijaId { get; set; }
        public Nullable<int> statusPlakatId { get; set; }
        public string dimenzija { get; set; }
        public Nullable<int> vrstaOkviraId { get; set; }
        public Nullable<int> dimenzijaId { get; set; }
        public Nullable<int> turaId { get; set; }
        public Nullable<int> zaposleniId { get; set; }
        public string akcija { get; set; }
        public Nullable<System.DateTime> vrijeme { get; set; }
        public int plakatLogId { get; set; }
    }
}
