//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ponudaKontakt
    {
        public int ponudaKontaktId { get; set; }
        public Nullable<int> ponudaId { get; set; }
        public Nullable<int> tipKontaktaId { get; set; }
        public string kontaktOsoba { get; set; }
        public string kontakt { get; set; }
    
        public virtual ponuda ponuda { get; set; }
    }
}
