//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ponudaStavke
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ponudaStavke()
        {
            this.fakturaStavke = new HashSet<fakturaStavke>();
            this.ponudaStavkaDodatak = new HashSet<ponudaStavkaDodatak>();
            this.radniNalogStavke = new HashSet<radniNalogStavke>();
        }
    
        public int ponudaStavkeId { get; set; }
        public Nullable<int> ponudaId { get; set; }
        public Nullable<int> plakatId { get; set; }
        public Nullable<int> trosakId { get; set; }
        public Nullable<decimal> kolicina { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<decimal> rabat { get; set; }
        public Nullable<decimal> cijenaSaPopustom { get; set; }
        public Nullable<decimal> cijenaDan { get; set; }
        public Nullable<int> mrezaId { get; set; }
        public Nullable<int> zaposleniId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fakturaStavke> fakturaStavke { get; set; }
        public virtual plakat plakat { get; set; }
        public virtual ponuda ponuda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ponudaStavkaDodatak> ponudaStavkaDodatak { get; set; }
        public virtual trosak trosak { get; set; }
        public virtual zaposleni zaposleni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<radniNalogStavke> radniNalogStavke { get; set; }
    }
}
