//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ponudaStavkeLog
    {
        public Nullable<int> ponudaStavkeId { get; set; }
        public Nullable<int> ponudaId { get; set; }
        public Nullable<int> plakatId { get; set; }
        public Nullable<int> trosakId { get; set; }
        public Nullable<decimal> kolicina { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<decimal> rabat { get; set; }
        public Nullable<decimal> cijenaSaPopustom { get; set; }
        public Nullable<int> mrezaId { get; set; }
        public Nullable<int> zaposleniId { get; set; }
        public string akcija { get; set; }
        public Nullable<System.DateTime> vrijeme { get; set; }
        public int ponudaStavkeLogId { get; set; }
    }
}
