//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class radniNalogStavke
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public radniNalogStavke()
        {
            this.radniNalogSlika = new HashSet<radniNalogSlika>();
        }
    
        public int radniNalogStavke1 { get; set; }
        public Nullable<int> radniNalogId { get; set; }
        public Nullable<int> ponudaStavkaId { get; set; }
        public string idejno { get; set; }
        public Nullable<bool> isPrijeLijepiti { get; set; }
        public string opis { get; set; }
        public Nullable<bool> isFotografisano { get; set; }
        public Nullable<int> turaSedmicaId { get; set; }
        public Nullable<bool> isDemontirano { get; set; }
        public Nullable<int> zaposleniId { get; set; }
    
        public virtual ponudaStavke ponudaStavke { get; set; }
        public virtual radniNalog radniNalog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<radniNalogSlika> radniNalogSlika { get; set; }
        public virtual turaSedmica turaSedmica { get; set; }
        public virtual zaposleni zaposleni { get; set; }
    }
}
