//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class radniNalogStavkeLog
    {
        public int radniNalogStavkeLog1 { get; set; }
        public Nullable<int> radniNalogStavke { get; set; }
        public Nullable<int> radniNalogId { get; set; }
        public Nullable<int> ponudaStavkaId { get; set; }
        public string idejno { get; set; }
        public Nullable<bool> isPrijeLijepiti { get; set; }
        public string opis { get; set; }
        public Nullable<bool> isFotografisano { get; set; }
        public Nullable<int> turaSedmicaId { get; set; }
        public Nullable<bool> isDemontirano { get; set; }
        public Nullable<int> zaposleniId { get; set; }
        public string akcija { get; set; }
        public Nullable<System.DateTime> vrijeme { get; set; }
    }
}
