//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trosak
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public trosak()
        {
            this.fakturaStavke = new HashSet<fakturaStavke>();
            this.ponudaStavkaDodatak = new HashSet<ponudaStavkaDodatak>();
            this.ponudaStavke = new HashSet<ponudaStavke>();
        }
    
        public int trosakId { get; set; }
        public string naziv { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<bool> aktivan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<fakturaStavke> fakturaStavke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ponudaStavkaDodatak> ponudaStavkaDodatak { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ponudaStavke> ponudaStavke { get; set; }
    }
}
