//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turaSedmicaZaposleni
    {
        public int turaSedmicaZaposleniId { get; set; }
        public Nullable<int> turaSedmicaId { get; set; }
        public Nullable<int> zaposleniId { get; set; }
    
        public virtual turaSedmica turaSedmica { get; set; }
        public virtual zaposleni zaposleni { get; set; }
    }
}
