//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turaSedmica
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public turaSedmica()
        {
            this.radniNalogStavke = new HashSet<radniNalogStavke>();
            this.turaSedmicaZaposleni = new HashSet<turaSedmicaZaposleni>();
        }
    
        public int turaSedmicaId { get; set; }
        public Nullable<int> turaId { get; set; }
        public Nullable<int> sedmicaId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<radniNalogStavke> radniNalogStavke { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turaSedmicaZaposleni> turaSedmicaZaposleni { get; set; }
    }
}
