//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ugovorLog
    {
        public int ugovorId { get; set; }
        public Nullable<System.DateTime> datumUgovora { get; set; }
        public Nullable<int> vlasnikId { get; set; }
        public Nullable<System.DateTime> pocetak { get; set; }
        public Nullable<System.DateTime> kraj { get; set; }
        public Nullable<decimal> vrijednost { get; set; }
        public Nullable<int> vrstaUgovoraId { get; set; }
        public string brojUgovora { get; set; }
        public Nullable<int> zaposleniId { get; set; }
        public string akcija { get; set; }
        public Nullable<System.DateTime> vrijeme { get; set; }
        public int ugovorLogId { get; set; }
    }
}
