//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ugovor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ugovor()
        {
            this.ugovorStavke = new HashSet<ugovorStavke>();
        }
    
        public int ugovorId { get; set; }
        public Nullable<System.DateTime> datumUgovora { get; set; }
        public Nullable<int> vlasnikId { get; set; }
        public Nullable<System.DateTime> pocetak { get; set; }
        public Nullable<System.DateTime> kraj { get; set; }
        public Nullable<decimal> vrijednost { get; set; }
        public Nullable<int> vrstaUgovoraId { get; set; }
        public string brojUgovora { get; set; }
        public Nullable<int> zaposleniId { get; set; }
    
        public virtual klijent klijent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ugovorStavke> ugovorStavke { get; set; }
        public virtual zaposleni zaposleni { get; set; }
    }
}
